### ISSUE TITLE
No docker in PATH: Check dependencies

### ISSUE THREAD

**Issue by laoyao** [yeasy/docker-hyperledger-fabric#3]
<img width="819" alt="2017-10-13 5 21 49" src="https://user-images.githubusercontent.com/870777/31539407-13cf56d2-afce-11e7-863e-6a3b3750be8a.png">

maybe the docker image was not install docker? Can't find any command about docker in repo's Dockfile.

**Comment by yeasy** [comment]
It's a run-time image, now a build-up one.

But if you wanna build peer binary locally, can try "bash /tmp/peer_build.sh" (take a look at /tmp).
