### ISSUE TITLE
panic: Version is not set for fabric-ca library

### ISSUE THREAD

**Issue by fasimito** [yeasy/docker-hyperledger-fabric#6]
when I fellow the guide to start the fabric-ca-server, get the next error:

=================================================
root@bogon:/home/fabrica# fabric-ca-server init -b admin:adminpw
2018/04/01 20:15:00 [INFO] Configuration file location: /home/fabrica/fabric-ca-server-config.yaml
panic: Version is not set for fabric-ca library

goroutine 1 [running]:
github.com/hyperledger/fabric-ca/lib/metadata.GetVersion(0x7791a7, 0xc4202b9200)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/lib/metadata/version.go:58 +0x60
github.com/hyperledger/fabric-ca/lib.(*Server).init(0xc4202b9200, 0xc4202de600, 0xf6c4f2, 0xc420141bf0)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/lib/server.go:98 +0x29
github.com/hyperledger/fabric-ca/lib.(*Server).Init(0xc4202b9200, 0xc4202b9200, 0x0, 0xc420141c50)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/lib/server.go:88 +0x38
main.(*ServerCmd).init.func2(0xc42018a240, 0xc420174660, 0x0, 0x2, 0x0, 0x0)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/servercmd.go:102 +0xfc
github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra.(*Command).execute(0xc42018a240, 0xc4201744c0, 0x2, 0x2, 0xc42018a240, 0xc4201744c0)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra/command.go:643 +0x3e8
github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42018a000, 0xd6e956, 0xc4201700f0, 0xc4201700f0)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra/command.go:734 +0x2fe
github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42018a000, 0xc420188000, 0xc4201700f0)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.(*ServerCmd).Execute(0xc4201700f0, 0x4, 0x1)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/servercmd.go:69 +0x2f
main.RunMain(0xc4200100c0, 0x4, 0x4, 0xc420141f70, 0xd7011b)
	/var/go/applications/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/main.go:45 +0xb0
main.main()
	/var/go/applications/src/github.com/hyperledger/fabric-ca/cmd/fabric-ca-server/main.go:27 +0x45
root@bogon:/home/fabrica# fabric-ca-server version
fabric-ca-server:
 Version: development build
 Go version: go1.9.2
 OS/Arch: linux/amd64

======================================================

so, what's the problem, could you give me some advice. thx.

**Comment by yeasy** [comment]
Pls try as following:

$ docker pull yeasy/hyperledger-fabric-ca:latest
$ docker run --rm -it yeasy/hyperledger-fabric-ca bash
 #fabric-ca-server init -b admin:adminpw

**Comment by fasimito** [comment]
I am sorry, I am not start it in the docker ,just start server natively and get the error, I would have a try the docker start.

**Comment by LeoMoonStar** [comment]
I tried to go through the natively start and find the same problem

**Comment by abhinay-b** [comment]
Same error.
